services:
  # 0. Dịch vụ tự động nạp backup (Chạy xong tự tắt)
  data-initializer:
    image: alpine:latest
    container_name: data-initializer
    volumes:
      - ./:/backup
      - dolibarr-data:/data/dolibarr
      - mysql-dolibarr-data:/data/mysql
      - invoiceshelf-data:/data/invoiceshelf-storage
      - invoiceshelf-db:/data/invoiceshelf-db
      - keycloak-data:/data/keycloak
    command: >
      sh -c "
        echo 'Đang nạp dữ liệu backup...' &&
        tar -xzf /backup/dolibarr-backup.tar.gz -C /data/dolibarr 2>/dev/null || true &&
        tar -xzf /backup/mysql-dolibarr-backup.tar.gz -C /data/mysql 2>/dev/null || true &&
        tar -xzf /backup/invoiceshelf-storage-backup.tar.gz -C /data/invoiceshelf-storage 2>/dev/null || true &&
        tar -xzf /backup/invoiceshelf-db-backup.tar.gz -C /data/invoiceshelf-db 2>/dev/null || true &&
        tar -xzf /backup/keycloak-db-backup.tar.gz -C /data/keycloak 2>/dev/null || true &&
        chmod -R 777 /data/keycloak &&
        echo 'Nạp dữ liệu thành công!'
      "

  # 1. Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev
    volumes:
      - keycloak-data:/opt/keycloak/data
    networks:
      - esb-network
    depends_on:
      data-initializer:
        condition: service_completed_successfully

  # 2. Dolibarr - ERP
  dolibarr:
    image: dolibarr/dolibarr:latest
    container_name: dolibarr
    environment:
      DOLI_DB_TYPE: mysqli
      DOLI_DB_HOST: mysql-dolibarr
      DOLI_DB_USER: root
      DOLI_DB_PASSWORD: root
      DOLI_DB_NAME: dolibarr
      DOLI_ADMIN_LOGIN: admin
      DOLI_ADMIN_PASSWORD: admin
    ports:
      - "8000:80"
    depends_on:
      data-initializer:
        condition: service_completed_successfully
      mysql-dolibarr:
        condition: service_healthy
    volumes:
      - dolibarr-data:/var/www/documents
    networks:
      - esb-network

  mysql-dolibarr:
    image: mysql:8
    container_name: mysql-dolibarr
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dolibarr
    volumes:
      - mysql-dolibarr-data:/var/lib/mysql
    networks:
      - esb-network
    depends_on:
      data-initializer:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      timeout: 20s
      retries: 10

  # 3. InvoiceShelf - Hóa đơn
  invoiceshelf:
    image: invoiceshelf/invoiceshelf:latest
    container_name: invoiceshelf
    environment:
      APP_URL: http://localhost:8002
      APP_DEBUG: "true"
      APP_ENV: local
      APP_KEY: "base64:kgk/4DW1vEVy7aEvet5FPp5un6PIGe/so8H0mvoUtW0="
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
      MAIL_MAILER: log
    ports:
      - "8002:8080"
    volumes:
      - invoiceshelf-data:/var/www/html/storage
      - invoiceshelf-db:/var/www/html/database
    networks:
      - esb-network
    depends_on:
      data-initializer:
        condition: service_completed_successfully

  # 4. WSO2 ESB
  wso2mi:
    image: wso2/wso2mi:4.2.0
    container_name: wso2mi
    ports:
      - "8290:8290"
      - "8243:8243"
    environment:
      - DOLIBARR_BASE_URL=http://dolibarr:80
      - DOLIBARR_TOKEN=59352f3754484dc66e9fae32e834ce40c2ea218e
      - EXPRESS_APP_BASE_URL=http://localhost:3000
      - INVOICE_SHELF_BASE_URL=http://invoiceshelf:8080
      - INVOICE_SHELF_PASSWORD=12345678
      - INVOICE_SHELF_TOKEN=1|sZQEMzN9q6f13YyYIEx5HGSZ5UoTuUTPhWuwplP96a08269c
      - INVOICE_SHELF_USER=admin@hethong.local
      - KEYCLOAK_BASE_URL=http://keycloak:8080
      - KEYCLOAK_CLIENT_SECRET=J3lsZQohEvnutdUpmbk2mqbcXiELtzIm
      # - LAKE_HOUSE_BASE_URL=http://localhost:4000
      - VNPAY_HASH_SECRET=14BD91DNB0D4YWYSQNRB5EFID0W0FOL1
      - VNPAY_TMN_CODE=ZERI53G9
      - WSO2_BASE_URL=http://localhost:8290
    volumes:
      - ./wso2-artifacts:/home/wso2carbon/wso2mi-4.2.0/repository/deployment/server/carbonapps
      - ./deployment.toml:/home/wso2carbon/wso2mi-4.2.0/conf/deployment.toml
    networks:
      - esb-network
    depends_on:
      - keycloak
      - dolibarr
      - invoiceshelf

  # 5. Giao diện bán hàng
  web-shop:
    build:
      context: ./web-shop
      dockerfile: Dockerfile
    container_name: web-shop
    ports:
      - "3000:3000"
    environment:
      - WSO2_BASE_URL=http://wso2mi:8290
      - KEYCLOAK_TOKEN_URL=http://keycloak:8080/realms/WSO2-Realm/protocol/openid-connect/token
      - CLIENT_ID=wso2-client
      - CLIENT_SECRET=J3lsZQohEvnutdUpmbk2mqbcXiELtzIm
    networks:
      - esb-network
    depends_on:
      - wso2mi

networks:
  esb-network:
    driver: bridge

volumes:
  dolibarr-data:
  mysql-dolibarr-data:
  invoiceshelf-data:   
  invoiceshelf-db:     
  keycloak-data: